language: python
sudo: enabled
python:
  - "3.6"

install:
  - npm install jasmine
  - sudo pip install -r requirements.txt
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar -xvzf geckodriver-v0.11.1-linux64.tar.gz
  - rm geckodriver-v0.11.1-linux64.tar.gz
  - chmod +x geckodriver
  - sudo cp geckodriver /usr/local/bin/

script:
  - cd server
  - sudo python -m pytest . --ignore=rhit-xprize-neural-network
  - cd ../2D\ Simulation
  - npx jasmine
  - cd ../server/
  - sudo python simulation.py &
  - sleep 30
  - cd ../e2e-tests/
  - sudo python -m pytest .
