* Blocksworld Server
The actual server to run that the Blocksworld client connects to.

To get started running the server locally, run the
=create-baseline.sql=, start up a PostgreSQL server on your machine,
then run =simulation.py= from this directory.

** PostgreSQL Details
There are three tables:
*** IBMDB
| IBMDB |      |   |   |   |    |    |    |    |    |    |   |
|-------+------+---+---+---+----+----+----+----+----+----+---|
| Time  | Task | b | W | G | bm | br | pn | pp | te | ie | p |

| IBMDB (cont.)   |             |             |            |               |
|-----------------+-------------+-------------+------------+---------------|
| TimeAndLocation | InitialInfo | SearchWords | finalScore | standard_info |

Records various details about the game, such as the final score and
how long it took to finish the game.
*** Human_Survey
| Human_Survey |    |    |    |    |    |
|--------------+----+----+----+----+----|
| q1           | q2 | q3 | q4 | q5 | q6 |

This holds the responses of the Commander to various exit survey
questions. Currently, few if any of these are used.
*** Robot_Survey
| Robot_Survey |    |    |
|--------------+----+----|
| q1           | q2 | q3 |

This holds the responses of the Worker to various exit survey
questions. Currently, few if any of these are used.
** Server Details
*** Configuration Files
The server loads it's configuration options from =commontConfig.json=
and, depending on whether the server is set up for local testing or
deployment, =localConfig.json= or =nonLocalConfig.json=. The non/local
configuration files mostly hold information about how to connect to
the database. The common configuration file that is always loaded
holds things like what port the server is created on.
