@startuml
Commander -> CommanderClient: "Makes gesture"
Commander -> CommanderClient: "Types message"
Commander -> CommanderClient: "Press Enter"
CommanderClient -> Server: receive_gesture_data
CommanderClient -> Server: receive_user_message
Server -> CommanderClient: update_user_message
CommanderClient -> Commander: "Display gesture and text"
Server -> CommanderClient: update_position({top_pos, left_pos, block_id})
CommanderClient -> Commander: "Update block's position"
Server -> CommanderClient: update_movement_data(move_number)
CommanderClient -> Commander: "Hide gesture"
Server -> CommanderClient: Update_score
Server -> CommanderClient: update_flip_block(block_id)
CommanderClient -> Commander: "Flip block"
Commander -> CommanderClient: "Press \"Incorrect Move\""
CommanderClient -> Server: incorrect_move
Server -> CommanderClient: update_position({top_pos, left_pos, block_id})
CommanderClient -> Commander: "Update block's position"
@enduml
