@startuml
Commander -> CommanderClient: "Makes gesture"
Commander -> CommanderClient: "Types message"
Commander -> CommanderClient: "Press Enter"
CommanderClient -> Server: receive_gesture_data
Server -> WorkerClient: update_gesture_data
CommanderClient -> Server: receive_user_message
Server -> CommanderClient: update_user_message
CommanderClient -> Commander: "Display gesture and text"
Server -> WorkerClient: update_user_message
WorkerClient -> Worker: "Display gesture and text"
Worker -> WorkerClient: "Move block"
WorkerClient -> Server: receive_position({top_pos, left_pos, block_id})
Server -> CommanderClient: update_position({top_pos, left_pos, block_id})
CommanderClient -> Commander: "Update block's position"
Worker -> WorkerClient: "Release block"
WorkerClient -> Server: receive_movement_data(move_number)
Server -> CommanderClient: update_movement_data(move_number)
CommanderClient -> Commander: "Hide gesture"
WorkerClient -> Server: Update_score
Server -> CommanderClient: Update_score
Worker -> WorkerClient: "Flip block"
WorkerClient -> Server: receive_flip_block(block_id)
Server -> CommanderClient: update_flip_block(block_id)
CommanderClient -> Commander: "Flip block"
@enduml
